### ISSUE TITLE
Arrays and conditions

### ISSUE THREAD

**Issue by sabooh26** [gordonmzhu/questions#167]
I have a general question: if (this.todos.length === 0) { console.log("array is empty"):}
//question is that if 0 is the first item of the array and 1 is the second, they how come we are comparing the length property to 0? wouldn't it mean if we have only 1 item in the array then the array index would equal to 0? I hope you can understand my question.

**Comment by gordonmzhu** [comment]
Can you explain what the length property is? From your question, it's not clear that you have a good understanding of length.

**Comment by gordonmzhu** [comment]
ping

**Comment by shellhatcher** [comment]
Hi, sabooh26!

First off all let's clarify the difference between  **.length** and the index position in an array.

1) .length refers to **the length of an array**, or in other words it shows the number of the "things" /how many stuffs inside an array, for example in the : 
var numbers = [0, 1, 2, 3];
The length of var numbers is 4 ( count from 0 to 3 )

another example
var candies = [ "lollipop", "chocopop", "cottoncandy"];
the length of the var candies is 3 (count from lollipop to cottoncandy)

2. Index in an array refers to the **position** of "a thing" in an array.
as for in the 
var numbers = [ 0, 1, 2, 3 ];
0 has index number of 0
1 has index number of 1
2 has index number of 2
3 has index number of 3

**index number or position in an array is counted from 0 instead of 1**

another example so that you might not get confused
 
var primeNumbers = [ 2, 3, 5];
Index number of 2 is 0
index number of 3 is 1
index number of 5 is 2

**So you see, it counts from 0 for index number.**

**For your question**
I have a general question: if (this.todos.length === 0) { console.log("array is empty"):}

That code doesn't meant to compare the length to 0, it's meant to check, if the length of the todos is equal to 0, which means at that point there is nothing inside the todos array, or in other words todos array is empty (remember that .length shows how many item inside an array, if there is nothing inside the array, it means the length of an array is 0 )
And if the condition being checked is true (the length of todos array is 0 or empty) it will print "array is empty"

Hopefully it can be of something useful, and sorry if my explanation is inaccurate.

**Comment by sabooh26** [comment]
thank you shellhatcher! that clears it out. I knew about the indexes of arrays but wasnt aware how it works in logic.
