### ISSUE TITLE
for loop issue

### ISSUE THREAD

**Issue by Madakin** [gordonmzhu/questions#186]
Hey,

So I've been working on the for loops section and it's telling me that todoText is undefinded. I've triple checked my work versus yours, can I honestly don't see any typos (and I have been pretty religious in checking for errors as I go). I could just be missing one out of frustration though. I have been using repl.it instead of plunker (I just find it easier to use). But when I copy the entire code into the console it says the same thing, so I don't think that's it. 

Anyway, here's my code. Please help.

https://repl.it/@Mdking2012/UnwillingShadyArchives

Thanks

Update: never mind, I figured it out. I wasn't recalling items correctly, so that made it weird.

**Comment by gordonmzhu** [comment]
Thanks for the update @Madakin. Also I should note that repl.it won't work later on because it's not a browser-based environment (repl.it uses Node, which is differerent). If you'd like to use something besides Plunker, follow the steps here instead: https://github.com/gordonmzhu/questions/issues/1.
