### ISSUE TITLE
todoList.deleteTodo does not work in version 10

### ISSUE THREAD

**Issue by dominick-designs** [gordonmzhu/questions#196]
### What is the associated Watch and Code lesson? 

version 10 (Clicking delete should update todoList.todos and the DOM)
https://watchandcode.com/courses/60264/lectures/1102313  (minute 4:40)

### Include a live demo link so that I can run your code. 

https://github.com/dominick-designs/practical-javascript/blob/master/script.js this is where the code is.   

here it is on codepen:  https://codepen.io/dominick_designs_websites/pen/MxYwYa?editors=1111

### Explain the exact steps I need to take to replicate the problem. 

line 165 : 

// why does handlers work here and not todoList.deleteTodo?
    
handlers.deleteTodo(parseInt(elementClicked.parentNode.id));

### What did you expect to happen? 

expected to delete item when clicking the button

### What actually happened? 

item was not deleted

### Describe what you've done so far to troubleshoot the problem. 

I tried todoList.deleteTodo instead of handlers.deleteTodo

**Comment by shellhatcher** [comment]
Hi, Dominick

Please correct me if I am wrong.

Try to use debugger to find out which deleteTodo() function is being used at line 167 of your code. It points to the deleteTodo() function inside the handlers object not the deleteTodo() function inside the todoList object.

There is a difference between deleteTodo() inside the todoList object and the deleteTodo() inside the handlers object.

**The one inside the handlers object  has the view.displaytodos()**

deleteTodo: function (position) {
		todoList.deleteTodo(position); 
		view.displaytodos();
	}
	
**The one inside the todoList object  doesn't have the view.displaytodos()**

deleteTodo: function(position) {
		this.todos.splice(position, 1);
            **//this function doesn't have the view.displaytodos()**
	}

if you use **todoList.deleteTodo() it will not include the view.displaytodos();** which is very important to create the <ul> ,<li>, and<button> with the class name "deleteButon" into the DOM.
that's why it didn't work, since the event listener works on the todosUL which was put in the DOM using the **view.displaytodos()**, and this function **only presents inside the handlers.deleteTodo()** not inside the todoList.deleteTodo()

Once again CMIW

**Comment by gordonmzhu** [comment]
Hey @dominick-designs were you able to figure this out? I deleted items on your codepen and didn't seem to run into any problems.

**Comment by dominick-designs** [comment]
Sorry! Please check line 167 — here https://codepen.io/dominick_designs_websites/pen/MxYwYa.

**Comment by dominick-designs** [comment]
Thank you @shellhatcher ! This helps me understand a lot better. 

You said:  "> Once again CMIW" 

What does CMIW mean?

**Comment by shellhatcher** [comment]
@dominick

Glad that it can help.
And as for CMIW, it stands for Correct Me If I am Wrong.
