### ISSUE TITLE
Confused about view and setUpEventListeners

### ISSUE THREAD

**Issue by lindaxiong** [gordonmzhu/questions#20]
### What is the associated Watch and Code lesson? 

https://watchandcode.com/courses/practical-javascript/lectures/1102313
version 10: clicking delete should update.. (2nd to last video)

### Include a live demo link so that I can run your code. 

https://glitch.com/edit/#!/sturdy-stew?path=public/client.js:128:49

### Explain the exact steps I need to take to replicate the problem. 

I didn't encounter bugs, but I'm confused about:
1) Why is that we need _views.setUpEventListeners();_ outside of everything for the setUpEventListeners to work, but we didn't do views.funcName() for the other functions in view. 

2) Why don't we put _setUpEventListeners: function()_ in var handlers = {}?

### What did you expect to happen? 

see above

### What actually happened? 

see above

### Describe what you've done so far to troubleshoot the problem. 

I thought through the code, but I still don't get why. I don't know where to go back to review about this since this isn't a concept at 1 time.

Thank you so much!

**Comment by gordonmzhu** [comment]
To address the first point:

```
Why is that we need views.setUpEventListeners(); outside of everything for the setUpEventListeners to work, but we didn't do views.funcName() for the other functions in view.
```

Think carefully about what causes each function to run.

- For example, when and how does `view.displayTodos` get called?
- When and how does `view.setUpEventListeners` get called?

**Comment by gordonmzhu** [comment]
To address the second point about where to put `setUpEventListeners`. That's just an organization issue. It's like if we had desks side by side and I put my stapler on my right but you put it on your left. Ultimately the same thing, just a different way to organize things.

**Comment by gordonmzhu** [comment]
Closing this issue since there hasn't been a reply for 3 days.

**Comment by ttorrisi** [comment]
Gordon - 

I didn't want to duplicate this issue, since I have basically the same question. The method call "view.setupEventListeners();' is just sitting at the end of my .js file. Having a bit of background in Java and C#, I wanted to see if I could clarify my understanding. Does any method that is called in a .js file automatically called when the page loads the .js file for the first time? Would this be the equivalent of executing a method in the main() method for Java or C#?

Thank you for your time, and I'm looking forward to continuing on after I wrap up the free Practical course! I've muddled around with OOP for a while (after being an ETL developer for a number of years), but have found that it only sticks when I'm learning and doing at the same time. I'm super excited to have found your course material.

Tim
