### ISSUE TITLE
Is passing the "event" parameter to the callback function of addEventListener compulsory?

### ISSUE THREAD

**Issue by trietjack** [gordonmzhu/questions#268]
### What is the associated Watch and Code lesson? 

https://watchandcode.com/courses/60264/lectures/1102312
Timestamp: 4:45

### Include a live demo link so that I can run your code. 

https://glitch.com/~todo-app-jack

### Explain the exact steps I need to take to replicate the problem. 

Just add and remove the "event" parameter in the callback function at line 106 of script.js.

### What did you expect to happen? 

When I removed the event parameter in the callback function, I expected that it would throw an error or it couldn't recognize the event in ```handlers.deleteTodo(parseInt(event.target.parentNode.id));```.

### What actually happened? 

It still runs normally.

### Describe what you've done so far to troubleshoot the problem. 

I tried to google search about this situation but it didn't give me the answer.

**Comment by gordonmzhu** [comment]
As your experiment showed, you don't need to, but leaving it out makes the code very confusing you would just have to know that event is there. Meanwhile the way the code is written creates a direct relationship to the parameter.

Instead of calling the parameter `event`, call it something else, like `myEvent` and then see how things change. You won't be able to delete the parameter, because it's being passed into `handlers.deleteTodo`.

**Comment by trietjack** [comment]
Thanks Gordon.
