### ISSUE TITLE
{{#This}} keyword in handlebars

### ISSUE THREAD

**Issue by polipix** [gordonmzhu/questions#3]
### What is the associated Watch and Code lesson? 

Write your response here (required).
https://watchandcode.com/courses/77710/lectures/1284592
timestamp 22:55 you introduce {{#this}} keyword in handlebars
### Include a live demo link so that I can run your code. 

Write your response here (required).
i think there is no need to provide my code as i don't have/ didn't found deeper knowledge on this topic i just tried to insert instead of {{#this}} {{#each}} and other variations. Would you be so kind to explain why this won't work in our case? 
### Explain the exact steps I need to take to replicate the problem. 

Write your response here (required).
I was just wondering how could we rewrite moustache code in <script id="todo-template"> where {{#this}} happens. I didn't understand it thoroughly so i wanted to write it in other way like many sources suggest using for example {{#each}}. Now i found that we need identifier that points to an array value such as "identifier: [array]". This page helped me to understand many nuances https://yuilibrary.com/yui/docs/handlebars/#each.

### What did you expect to happen? 

Write your response here (required).
I just wanted to recreate our handlebars code using other way, just to get exactly the same output without or with minimal changes in js. I thought that {{#each}} helper will solve the case.
As whenever you search informations about iterating through array in handlebars, there is advice that you should use {{#each}} and in our case we use mysterious {{#this}}. I know that we are passing array like you say directly and we set up context while looping to certain element, but my main question is why we cannot use {{#each}} here.
### What actually happened? 

Write your response here (required).
When i tried to use {{#each}} or other crazy variations it was adding items to active items but i couldn't use {{title}}, {{id}} or other properties in todo app.
### Describe what you've done so far to troubleshoot the problem. 

Write your response here (required).
Used debugger tried many stupid blind experiments without any deeper knowledge mainly tried to follow handlebars documentation, stackoverflow and https://yuilibrary.com/yui/docs/handlebars/#each which helped me to interprete this behavior

**Comment by gordonmzhu** [comment]
As requested in the template, you need to provide an actual code example so that we have some code to discuss and troubleshoot. Your question is currently too general and vague for me to answer.

You are also confusing a bunch of different things. For example, Handlebars is not Moustache. The YUI version of Handlebars is NOT the same as the original Handlebars, so stick with the original documentation for Handlebars, not the YUI version.

In "What actually happened" you describe a situation but do not share the code that you used. Again, this is related to not including any code in your question as I mentioned before. That is why each section is required.

If you'd like an answer, please re-open this issue and provide answers for every part of the questions template. For example, I attempted to get this snippet of code to work. I got X when I expected Y. I did these things to try to figure things out on my own.
