### ISSUE TITLE
Chapter 7. adding event listener

### ISSUE THREAD

**Issue by vinitrai** [gordonmzhu/questions#315]
Hi Gordon,
Thanks for the wonderful tutorials, my issue is not a technical one but its a conceptual one.I am not getting a concept so I thought of asking you.
In version 7-HTML and the DOM chapter of 'Practical Javascript' series when you applied a click event to the displayTodosButton it worked fine and I understood it.
The code is
displayTodosButton.addEventListener('click',function(){
  todoList.displayTodos();
});
but, when I try calling the method directly without an anonymous function in the event listener it doesn't work.
displayTodosButton.addEventListener('click',todoList.displayTodos);

This is too confusing for me,please help.

**Comment by gordonmzhu** [comment]
What's the error message that you get? This is why you need to fill out all the fields that are in the template. I also can't run your code since you didn't provide it. If you'd like to continue the discussion, open a new issue and fill out all the fields, which are required (that is why they are labeled *required*).
