### ISSUE TITLE
displayTodos access to .completed in the toggleCompleted function.

### ISSUE THREAD

**Issue by barry505** [gordonmzhu/questions#346]
### What is the associated Watch and Code lesson? 

Version 5 - displayTodos should show .completed

### Include a live demo link so that I can run your code. 

My code works

### Explain the exact steps I need to take to replicate the problem. 

How does the if statement in the displayTodos function have access to the '.completed' in the toggleCompleted function.

**Comment by gordonmzhu** [comment]
You want to look at things differently. It'll help to review this section "Interlude - Functions and variables".

https://watchandcode.com/courses/60264/lectures/4350603

In the `displayTodos` method, you're accessing `this.todos`. Take a look at `this.todos` in the console so that you can see what it looks like.
