### ISSUE TITLE
Error message in google chrome console

### ISSUE THREAD

**Issue by TiemaCouly** [gordonmzhu/questions#347]
### What is the associated Watch and Code lesson? https://watchandcode.com/courses/60264/lectures/900211

Write your response here (required).

### Include a live demo link so that I can run your code. 
https://plnkr.co/edit/cQEOBU5suO4BHg1G?p=preview
Write your response here (required).

### Explain the exact steps I need to take to replicate the problem. 

Write your response here (required).
I followed step by step the video without adding anything I tried only on chrome I don't have safari
### What did you expect to happen? 

Write your response here (required).

### What actually happened? 

Write your response here (required).

### Describe what you've done so far to troubleshoot the problem. 
I try to review the code many time checked my google chrome but couldn't find from where the error is
Write your response here (required).
I've attached a screenshot of the page error
![Screenshot (35)](https://user-images.githubusercontent.com/47168830/70853562-a2f07880-1eaf-11ea-828d-d8f5582f5712.png)
![Screenshot (35)](https://user-images.githubusercontent.com/47168830/70853569-b1d72b00-1eaf-11ea-89a2-64ce1de77984.png)

**Comment by gordonmzhu** [comment]
Hey @TiemaCouly. Try this project link instead and things should work. Plunker has a weird issue where if the `package.json` file isn't an empty object. It can mess things up. All I did was change the package.json so it's an empty object: https://plnkr.co/edit/uXfz40ammGfpUMOxQFfb?p=preview.

That should solve things for now, but If you'd prefer to use something instead of Plunker, see #1.
