### ISSUE TITLE
This question is in reference to Version 4: Booleans, under todolist.addTodo should add objects. My question is written in the comments section.

### ISSUE THREAD

**Issue by Roman4u** [gordonmzhu/questions#385]
### What is the associated Watch and Code lesson? 

Write your response here (required).

### Include a link to your code so I can run it on my computer. 

Write your response here (required).

### Explain the exact steps I need to take to replicate the problem. 

Write your response here (required).

### What did you expect to happen? 

Write your response here (required).

### What actually happened? 

Write your response here (required).

### Describe what you've done so far to troubleshoot the problem. 

Write your response here (required).

**Comment by Roman4u** [comment]
This question is in reference to Version 4: Booleans, under todolist.addTodo should add objects. There are several aspects of this tutorial which are a bit complicated, and would like some clarification.

1.  Appropriate terminology: the new object - along with its properties and values - are parameters of the push command, is that correct? And under (or on) this new object, the value of the todoText property is equal to whatever parameter is passed into the addTodo function()? Also the addTodo function() is technically called a method because it's a function that is a property on an object. I want to make sure I understand this correctly and am using the appropriate terminology to explain it.

2. When display todolist.addTodo runs on the console, specifically at 4:08, Gordon states, "our todos array is now an array of objects." This is what's displayed:

todolist.addTodo('This is an object.');
                   My todos [object]
                                       0: object
                                              completed: false
                                              todoText: This is an object

I'm confused since the values for the todos property (a property which is an array) were all deleted at 1:50, which left the array blank. So, I don't understand how there is an object at the 0 position of an array when our array is literally blank. Essentially, I don't understand how this new object has become an array (or is referencing the blank todos array) when there are no [ ] within this new object indicating that it is functioning as an array. Does this all make sense?

**Comment by gordonmzhu** [comment]
Question: "the new object - along with its properties and values - are parameters of the push command, is that correct?"

Answer: No. The object passed into `.push` is an "argument".

Question: And under (or on) this new object, the value of the todoText property is equal to whatever parameter is passed into the addTodo function()?

Answer: You can answer this question. This is easily verifiable with a simple test. 

Question: Also the addTodo function() is technically called a method because it's a function that is a property on an object.

Answer: See https://watchandcode.com/courses/60264/lectures/900210.

Question: Since the new object (with properties todoText and completed) is a parameter of the push command, the values we give these two properties will be added to, or pushed onto, the todo array. Is this correct?

Answer: Before you run the `add` method, how many items are in the array? Zero. Then, as you know, `.push` adds things to an array. So if you `.push` an object to the array well, the array will now have the item that you just pushed to it.
