### ISSUE TITLE
Having some issues

### ISSUE THREAD

**Issue by cerlans** [gordonmzhu/questions#400]
### What is the associated Watch and Code lesson? 

Write your response here (required).
https://watchandcode.com/courses/60264/lectures/1056225
3:30 after your done making the entire for loop. 
### Include a link to your code so I can run it on my computer. 

Write your response here (required).
https://gist.github.com/cerlans/c0fb17adb8a6280b5a2208f375fa0d3e

### Explain the exact steps I need to take to replicate the problem. 

Write your response here (required).
**i've followed the syntax layed out in the video almost to its entirety, with some changes to variable names and such, nothing big.
Everytime i try to create the VIEW object, along with the query selector and than appending it, i get this error 
Uncaught DOMException: Failed to execute 'appendChild' on 'Node': Only one element on document allowed.**
### What did you expect to happen? 
Write your response here (required).
I expected the program to be error free as i haven't made any modifications to the code, except names, i've tried hours already looking for the problem.

### What actually happened? 

Write your response here (required).
**var view = {
  displayTodos: function() {
    var todosUl = document.querySelector('ul');
    todosUl.innerHTML= '';
    for (var i = 0; i <todoList.todos.length;i++) {
    var todosLi = document.createElement('li');
    var todosUl = document.appendChild(todosLi);
    
    }
  }
}
Uncaught DOMException: Failed to execute 'appendChild' on 'Node': Only one element on document allowed.****

### Describe what you've done so far to troubleshoot the problem. 

Write your response here (required).
i've appended .body after the Document, and that seems to have fixed the problem, but than a new problem came up later in the code , and that was the INNERHTML method not working.

**Comment by gordonmzhu** [comment]
How can I replicate the problem so that I get the same error as you?

**Comment by gordonmzhu** [comment]
A couple of additional notes. 

(1) Your code is definitely not the same. I recommend going through character by character so that you can see the differences. Don't change variables, there's no benefit in doing so. If you really want to do this, you can do it after you have everything working at the end of the course.

(2) Your code is very hard to read because it does not follow the style that I demonstrate in the course. Again, if you make sure the code is the same as mine, you would not have this issue. Make sure you adhere to the same style.

(3) If you do (1) and (2), it will solve any issues you have.
